name: Deploy API Gateway Application
'on':
  workflow_dispatch: {}
env:
  # Secrets
  HOST: '${{ secrets.HOST }}'
  USERNAME: '${{ secrets.USERNAME }}'
  PASSWORD: '${{ secrets.PASSWORD }}'
  APIGATEWAY_DB_HOST: '${{ secrets.APIGATEWAY_DB_HOST }}'
  APIGATEWAY_ADMIN_DB_PASSWORD: '${{ secrets.APIGATEWAY_ADMIN_DB_PASSWORD }}'
  REMOTE_API_GATEWAY_DIRECTORY: '${{ secrets.REMOTE_API_GATEWAY_DIRECTORY }}'
  GTHB_PAT: '${{ secrets.GTHB_PAT }}'  

  # Variables
  MODE: prod

jobs:
  deploy:
    name: Deploying API_GATEWAY application
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Update submodule
        run: git submodule update --recursive --remote

      - name: Create ssh directory
        run: mkdir ~/.ssh

      - name: Add ssh known hosts
        run: ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - name: Copy contents of password to SSH key
        run: echo "$PASSWORD" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && chmod 700 ~/.ssh


      - name: Generate env file
        run: |
          echo "ASPNETCORE_ENVIRONMENT=$MODE" >> .env
          echo "APPLICATION_HOST=https://vip3rtech6069.com:8005" >> .env
          echo "DB_HOST=$APIGATEWAY_DB_HOST" >> .env
          echo "DB_USERNAME=sa" >> .env
          echo "DB_PASSWORD=$APIGATEWAY_ADMIN_DB_PASSWORD" >> .env
          echo "DB_ENCRYPT=True" >> .env
          echo "DB_TRUSTSERVERCERTIFICATE=True" >> .env
          cat .env
        working-directory: ThePortfolioGateway

      - name: Deploy Resource Management Application
        run: |
          chmod +x build-tools/deployment.sh && ./build-tools/deployment.sh -m $MODE -i $HOST -u $USERNAME -s ~/.ssh/id_rsa -c authenticationservice -d $(pwd) -a ThePortfolioGateway -r "$REMOTE_API_GATEWAY_DIRECTORY"
        working-directory: ThePortfolioGateway