services:
  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile

    container_name: gatewayservice

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - APPLICATION_HOST=http://gatewayservice:8005
      - IS_DOCKER_ENVIRONMENT=true

    ports:
      - "8005:8005"

    networks:
      - platform_net

networks:
  platform_net:
    driver: bridge
    name: my-portfolio-network
    external: true
